apiVersion: apps/v1
kind: Deployment
metadata:
  name: revspeed-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revspeed-backend
  template:
    metadata:
      labels:
        app: revspeed-backend
    spec:
      containers:
        - name: revspeed-backend
          image: gcr.io/PROJECT_ID/IMAGE/TAG
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_PASSWORD
