apiVersion: apps/v1
kind: Deployment
metadata:
  name: revspeed-gke
  labels:
    app: revspeed-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revspeed-gke
  template:
    metadata:
      labels:
        app: revspeed-gke
    spec:
      containers:
        - name: revspeed-gke-container
          image: us-central1-docker.pkg.dev/revspeed16/my-repo/revspeed-gke-image:1.0.0  # Use your image details
          ports:
            - containerPort: 8080
#          env:
#            - name: DATABASE_URL
#              valueFrom:
#                secretKeyRef:
#                  name: db-credentials
#                  key: mysql://root:2001@34.93.16.141:3306/revspeed_db
#            - name: DATABASE_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: db-credentials
#                  key: root
#            - name: DATABASE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: db-credentials
#                  key: 2001
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
