apiVersion: apps/v1
kind: Deployment
metadata:
  name: revspeed-gke
  labels:
    app: revspeed-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revspeed-gke
  template:
    metadata:
      labels:
        app: revspeed-gke
    spec:
      containers:
        - name: revspeed-gke-container
          image: us-central1-docker.pkg.dev/revspeed16/my-repo/revspeed-gke-image:1.0.0  # Use your image details
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
