apiVersion: v1
kind: Service
metadata:
  name: revspeed-backend-service
spec:
  type: LoadBalancer
  selector:
    app: revspeed-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
